# Generated by Django 2.0.5 on 2018-05-17 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('ingredient1', models.CharField(max_length=1024)),
                ('ingredient2', models.CharField(max_length=1024, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
