# Generated by Django 2.0.4 on 2018-05-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('serving_size', models.IntegerField(default=0)),
                ('calories', models.FloatField(default=0.0)),
                ('weight', models.FloatField(default=0.0)),
                ('ingredients', models.CharField(max_length=1024)),
                ('image', models.URLField()),
                ('total_nutrients', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RemoveField(
            model_name='mymovie',
            name='owner',
        ),
        migrations.DeleteModel(
            name='MyMovie',
        ),
    ]
