# Generated by Django 2.0.4 on 2018-05-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_myrecipe_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myrecipe',
            old_name='source',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='myrecipe',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='myrecipe',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='myrecipe',
            old_name='serving_size',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='myrecipe',
            old_name='ingredients',
            new_name='producer',
        ),
        migrations.RemoveField(
            model_name='myrecipe',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='myrecipe',
            name='total_nutrients',
        ),
        migrations.RemoveField(
            model_name='myrecipe',
            name='url',
        ),
        migrations.RemoveField(
            model_name='myrecipe',
            name='weight',
        ),
    ]
